import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import VerticalNav from "./components/Navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased grid md:grid-cols-7 m-12 lg:my-12 lg:mx-25 gap-12`}
      >
        <VerticalNav></VerticalNav> {children}
      </body>
    </html>
  );
}
